/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.daos;


import com.wl.myshrio.generator.jooq.tables.SysAttributeDetail;
import com.wl.myshrio.generator.jooq.tables.records.SysAttributeDetailRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAttributeDetailDao extends DAOImpl<SysAttributeDetailRecord, com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail, String> {

    /**
     * Create a new SysAttributeDetailDao without any configuration
     */
    public SysAttributeDetailDao() {
        super(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL, com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail.class);
    }

    /**
     * Create a new SysAttributeDetailDao with an attached configuration
     */
    public SysAttributeDetailDao(Configuration configuration) {
        super(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL, com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail> fetchById(String... values) {
        return fetch(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail fetchOneById(String value) {
        return fetchOne(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.ID, value);
    }

    /**
     * Fetch records that have <code>attrId IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail> fetchByAttrid(String... values) {
        return fetch(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.ATTRID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysAttributeDetail> fetchByName(String... values) {
        return fetch(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.NAME, values);
    }
}
