/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.daos;


import com.wl.myshrio.generator.jooq.tables.SysAttribute;
import com.wl.myshrio.generator.jooq.tables.records.SysAttributeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAttributeDao extends DAOImpl<SysAttributeRecord, com.wl.myshrio.generator.jooq.tables.pojos.SysAttribute, String> {

    /**
     * Create a new SysAttributeDao without any configuration
     */
    public SysAttributeDao() {
        super(SysAttribute.SYS_ATTRIBUTE, com.wl.myshrio.generator.jooq.tables.pojos.SysAttribute.class);
    }

    /**
     * Create a new SysAttributeDao with an attached configuration
     */
    public SysAttributeDao(Configuration configuration) {
        super(SysAttribute.SYS_ATTRIBUTE, com.wl.myshrio.generator.jooq.tables.pojos.SysAttribute.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wl.myshrio.generator.jooq.tables.pojos.SysAttribute object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysAttribute> fetchById(String... values) {
        return fetch(SysAttribute.SYS_ATTRIBUTE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wl.myshrio.generator.jooq.tables.pojos.SysAttribute fetchOneById(String value) {
        return fetchOne(SysAttribute.SYS_ATTRIBUTE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysAttribute> fetchByName(String... values) {
        return fetch(SysAttribute.SYS_ATTRIBUTE.NAME, values);
    }
}
