/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.daos;


import com.wl.myshrio.generator.jooq.tables.SysOperatingRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysOperatingRecordRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysOperatingRecordDao extends DAOImpl<SysOperatingRecordRecord, com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord, String> {

    /**
     * Create a new SysOperatingRecordDao without any configuration
     */
    public SysOperatingRecordDao() {
        super(SysOperatingRecord.SYS_OPERATING_RECORD, com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord.class);
    }

    /**
     * Create a new SysOperatingRecordDao with an attached configuration
     */
    @Autowired
    public SysOperatingRecordDao(Configuration configuration) {
        super(SysOperatingRecord.SYS_OPERATING_RECORD, com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchById(String... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord fetchOneById(String value) {
        return fetchOne(SysOperatingRecord.SYS_OPERATING_RECORD.ID, value);
    }

    /**
     * Fetch records that have <code>requestUrl IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchByRequesturl(String... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.REQUESTURL, values);
    }

    /**
     * Fetch records that have <code>remoteAddr IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchByRemoteaddr(String... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.REMOTEADDR, values);
    }

    /**
     * Fetch records that have <code>params IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchByParams(String... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.PARAMS, values);
    }

    /**
     * Fetch records that have <code>method IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchByMethod(String... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.METHOD, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchByCreateTime(LocalDateTime... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>uid IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchByUid(String... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.UID, values);
    }

    /**
     * Fetch records that have <code>flag IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysOperatingRecord> fetchByFlag(String... values) {
        return fetch(SysOperatingRecord.SYS_OPERATING_RECORD.FLAG, values);
    }
}
