/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.daos;


import com.wl.myshrio.generator.jooq.tables.SysPermission;
import com.wl.myshrio.generator.jooq.tables.records.SysPermissionRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysPermissionDao extends DAOImpl<SysPermissionRecord, com.wl.myshrio.generator.jooq.tables.pojos.SysPermission, String> {

    /**
     * Create a new SysPermissionDao without any configuration
     */
    public SysPermissionDao() {
        super(SysPermission.SYS_PERMISSION, com.wl.myshrio.generator.jooq.tables.pojos.SysPermission.class);
    }

    /**
     * Create a new SysPermissionDao with an attached configuration
     */
    @Autowired
    public SysPermissionDao(Configuration configuration) {
        super(SysPermission.SYS_PERMISSION, com.wl.myshrio.generator.jooq.tables.pojos.SysPermission.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wl.myshrio.generator.jooq.tables.pojos.SysPermission object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchById(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wl.myshrio.generator.jooq.tables.pojos.SysPermission fetchOneById(String value) {
        return fetchOne(SysPermission.SYS_PERMISSION.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByName(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.NAME, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByUrl(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.URL, values);
    }

    /**
     * Fetch records that have <code>requestType IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByRequesttype(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.REQUESTTYPE, values);
    }

    /**
     * Fetch records that have <code>fatherId IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByFatherid(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.FATHERID, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchBySort(Integer... values) {
        return fetch(SysPermission.SYS_PERMISSION.SORT, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByType(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.TYPE, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByCreateTime(LocalDateTime... values) {
        return fetch(SysPermission.SYS_PERMISSION.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(SysPermission.SYS_PERMISSION.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>creater IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByCreater(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.CREATER, values);
    }

    /**
     * Fetch records that have <code>updater IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByUpdater(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.UPDATER, values);
    }

    /**
     * Fetch records that have <code>iconCls IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysPermission> fetchByIconcls(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.ICONCLS, values);
    }
}
