/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.daos;


import com.wl.myshrio.generator.jooq.tables.SysRole;
import com.wl.myshrio.generator.jooq.tables.records.SysRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleDao extends DAOImpl<SysRoleRecord, com.wl.myshrio.generator.jooq.tables.pojos.SysRole, String> {

    /**
     * Create a new SysRoleDao without any configuration
     */
    public SysRoleDao() {
        super(SysRole.SYS_ROLE, com.wl.myshrio.generator.jooq.tables.pojos.SysRole.class);
    }

    /**
     * Create a new SysRoleDao with an attached configuration
     */
    public SysRoleDao(Configuration configuration) {
        super(SysRole.SYS_ROLE, com.wl.myshrio.generator.jooq.tables.pojos.SysRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wl.myshrio.generator.jooq.tables.pojos.SysRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysRole> fetchById(String... values) {
        return fetch(SysRole.SYS_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wl.myshrio.generator.jooq.tables.pojos.SysRole fetchOneById(String value) {
        return fetchOne(SysRole.SYS_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysRole> fetchByName(String... values) {
        return fetch(SysRole.SYS_ROLE.NAME, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysRole> fetchByDescription(String... values) {
        return fetch(SysRole.SYS_ROLE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysRole> fetchByType(Integer... values) {
        return fetch(SysRole.SYS_ROLE.TYPE, values);
    }
}
