/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.daos;


import com.wl.myshrio.generator.jooq.tables.SysUserRole;
import com.wl.myshrio.generator.jooq.tables.records.SysUserRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysUserRoleDao extends DAOImpl<SysUserRoleRecord, com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole, String> {

    /**
     * Create a new SysUserRoleDao without any configuration
     */
    public SysUserRoleDao() {
        super(SysUserRole.SYS_USER_ROLE, com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole.class);
    }

    /**
     * Create a new SysUserRoleDao with an attached configuration
     */
    @Autowired
    public SysUserRoleDao(Configuration configuration) {
        super(SysUserRole.SYS_USER_ROLE, com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole> fetchById(String... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole fetchOneById(String value) {
        return fetchOne(SysUserRole.SYS_USER_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>uid IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole> fetchByUid(String... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.UID, values);
    }

    /**
     * Fetch records that have <code>rid IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUserRole> fetchByRid(String... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.RID, values);
    }
}
