/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.daos;


import com.wl.myshrio.generator.jooq.tables.SysUser;
import com.wl.myshrio.generator.jooq.tables.records.SysUserRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserDao extends DAOImpl<SysUserRecord, com.wl.myshrio.generator.jooq.tables.pojos.SysUser, String> {

    /**
     * Create a new SysUserDao without any configuration
     */
    public SysUserDao() {
        super(SysUser.SYS_USER, com.wl.myshrio.generator.jooq.tables.pojos.SysUser.class);
    }

    /**
     * Create a new SysUserDao with an attached configuration
     */
    public SysUserDao(Configuration configuration) {
        super(SysUser.SYS_USER, com.wl.myshrio.generator.jooq.tables.pojos.SysUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.wl.myshrio.generator.jooq.tables.pojos.SysUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchById(String... values) {
        return fetch(SysUser.SYS_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wl.myshrio.generator.jooq.tables.pojos.SysUser fetchOneById(String value) {
        return fetchOne(SysUser.SYS_USER.ID, value);
    }

    /**
     * Fetch records that have <code>head_portraits IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchByHeadPortraits(String... values) {
        return fetch(SysUser.SYS_USER.HEAD_PORTRAITS, values);
    }

    /**
     * Fetch records that have <code>nickname IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchByNickname(String... values) {
        return fetch(SysUser.SYS_USER.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchByEmail(String... values) {
        return fetch(SysUser.SYS_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>pswd IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchByPswd(String... values) {
        return fetch(SysUser.SYS_USER.PSWD, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchByCreateTime(LocalDateTime... values) {
        return fetch(SysUser.SYS_USER.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>last_login_time IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchByLastLoginTime(LocalDateTime... values) {
        return fetch(SysUser.SYS_USER.LAST_LOGIN_TIME, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.wl.myshrio.generator.jooq.tables.pojos.SysUser> fetchByStatus(Long... values) {
        return fetch(SysUser.SYS_USER.STATUS, values);
    }
}
