/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq;


import com.wl.myshrio.generator.jooq.tables.SysAttribute;
import com.wl.myshrio.generator.jooq.tables.SysAttributeDetail;
import com.wl.myshrio.generator.jooq.tables.SysLoginLog;
import com.wl.myshrio.generator.jooq.tables.SysOperatingRecord;
import com.wl.myshrio.generator.jooq.tables.SysPermission;
import com.wl.myshrio.generator.jooq.tables.SysRole;
import com.wl.myshrio.generator.jooq.tables.SysRolePermission;
import com.wl.myshrio.generator.jooq.tables.SysUser;
import com.wl.myshrio.generator.jooq.tables.SysUserRole;
import com.wl.myshrio.generator.jooq.tables.records.SysAttributeDetailRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysAttributeRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysLoginLogRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysOperatingRecordRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysPermissionRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysRolePermissionRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysRoleRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysUserRecord;
import com.wl.myshrio.generator.jooq.tables.records.SysUserRoleRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>shrio</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SysAttributeRecord> KEY_SYS_ATTRIBUTE_PRIMARY = UniqueKeys0.KEY_SYS_ATTRIBUTE_PRIMARY;
    public static final UniqueKey<SysAttributeDetailRecord> KEY_SYS_ATTRIBUTE_DETAIL_PRIMARY = UniqueKeys0.KEY_SYS_ATTRIBUTE_DETAIL_PRIMARY;
    public static final UniqueKey<SysLoginLogRecord> KEY_SYS_LOGIN_LOG_PRIMARY = UniqueKeys0.KEY_SYS_LOGIN_LOG_PRIMARY;
    public static final UniqueKey<SysOperatingRecordRecord> KEY_SYS_OPERATING_RECORD_PRIMARY = UniqueKeys0.KEY_SYS_OPERATING_RECORD_PRIMARY;
    public static final UniqueKey<SysPermissionRecord> KEY_SYS_PERMISSION_PRIMARY = UniqueKeys0.KEY_SYS_PERMISSION_PRIMARY;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PRIMARY;
    public static final UniqueKey<SysRolePermissionRecord> KEY_SYS_ROLE_PERMISSION_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PERMISSION_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = UniqueKeys0.KEY_SYS_USER_PRIMARY;
    public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<SysAttributeRecord> KEY_SYS_ATTRIBUTE_PRIMARY = Internal.createUniqueKey(SysAttribute.SYS_ATTRIBUTE, "KEY_sys_attribute_PRIMARY", SysAttribute.SYS_ATTRIBUTE.ID);
        public static final UniqueKey<SysAttributeDetailRecord> KEY_SYS_ATTRIBUTE_DETAIL_PRIMARY = Internal.createUniqueKey(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL, "KEY_sys_attribute_detail_PRIMARY", SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.ID);
        public static final UniqueKey<SysLoginLogRecord> KEY_SYS_LOGIN_LOG_PRIMARY = Internal.createUniqueKey(SysLoginLog.SYS_LOGIN_LOG, "KEY_sys_login_log_PRIMARY", SysLoginLog.SYS_LOGIN_LOG.ID);
        public static final UniqueKey<SysOperatingRecordRecord> KEY_SYS_OPERATING_RECORD_PRIMARY = Internal.createUniqueKey(SysOperatingRecord.SYS_OPERATING_RECORD, "KEY_sys_operating_record_PRIMARY", SysOperatingRecord.SYS_OPERATING_RECORD.ID);
        public static final UniqueKey<SysPermissionRecord> KEY_SYS_PERMISSION_PRIMARY = Internal.createUniqueKey(SysPermission.SYS_PERMISSION, "KEY_sys_permission_PRIMARY", SysPermission.SYS_PERMISSION.ID);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = Internal.createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_PRIMARY", SysRole.SYS_ROLE.ID);
        public static final UniqueKey<SysRolePermissionRecord> KEY_SYS_ROLE_PERMISSION_PRIMARY = Internal.createUniqueKey(SysRolePermission.SYS_ROLE_PERMISSION, "KEY_sys_role_permission_PRIMARY", SysRolePermission.SYS_ROLE_PERMISSION.ID);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = Internal.createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_PRIMARY", SysUser.SYS_USER.ID);
        public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = Internal.createUniqueKey(SysUserRole.SYS_USER_ROLE, "KEY_sys_user_role_PRIMARY", SysUserRole.SYS_USER_ROLE.ID);
    }
}
