/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq;


import com.wl.myshrio.generator.jooq.tables.SysAttribute;
import com.wl.myshrio.generator.jooq.tables.SysAttributeDetail;
import com.wl.myshrio.generator.jooq.tables.SysLoginLog;
import com.wl.myshrio.generator.jooq.tables.SysOperatingRecord;
import com.wl.myshrio.generator.jooq.tables.SysPermission;
import com.wl.myshrio.generator.jooq.tables.SysRole;
import com.wl.myshrio.generator.jooq.tables.SysRolePermission;
import com.wl.myshrio.generator.jooq.tables.SysUser;
import com.wl.myshrio.generator.jooq.tables.SysUserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shrio extends SchemaImpl {

    private static final long serialVersionUID = 293568442;

    /**
     * The reference instance of <code>shrio</code>
     */
    public static final Shrio SHRIO = new Shrio();

    /**
     * The table <code>shrio.sys_attribute</code>.
     */
    public final SysAttribute SYS_ATTRIBUTE = com.wl.myshrio.generator.jooq.tables.SysAttribute.SYS_ATTRIBUTE;

    /**
     * The table <code>shrio.sys_attribute_detail</code>.
     */
    public final SysAttributeDetail SYS_ATTRIBUTE_DETAIL = com.wl.myshrio.generator.jooq.tables.SysAttributeDetail.SYS_ATTRIBUTE_DETAIL;

    /**
     * The table <code>shrio.sys_login_log</code>.
     */
    public final SysLoginLog SYS_LOGIN_LOG = com.wl.myshrio.generator.jooq.tables.SysLoginLog.SYS_LOGIN_LOG;

    /**
     * The table <code>shrio.sys_operating_record</code>.
     */
    public final SysOperatingRecord SYS_OPERATING_RECORD = com.wl.myshrio.generator.jooq.tables.SysOperatingRecord.SYS_OPERATING_RECORD;

    /**
     * The table <code>shrio.sys_permission</code>.
     */
    public final SysPermission SYS_PERMISSION = com.wl.myshrio.generator.jooq.tables.SysPermission.SYS_PERMISSION;

    /**
     * The table <code>shrio.sys_role</code>.
     */
    public final SysRole SYS_ROLE = com.wl.myshrio.generator.jooq.tables.SysRole.SYS_ROLE;

    /**
     * The table <code>shrio.sys_role_permission</code>.
     */
    public final SysRolePermission SYS_ROLE_PERMISSION = com.wl.myshrio.generator.jooq.tables.SysRolePermission.SYS_ROLE_PERMISSION;

    /**
     * The table <code>shrio.sys_user</code>.
     */
    public final SysUser SYS_USER = com.wl.myshrio.generator.jooq.tables.SysUser.SYS_USER;

    /**
     * The table <code>shrio.sys_user_role</code>.
     */
    public final SysUserRole SYS_USER_ROLE = com.wl.myshrio.generator.jooq.tables.SysUserRole.SYS_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Shrio() {
        super("shrio", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SysAttribute.SYS_ATTRIBUTE,
            SysAttributeDetail.SYS_ATTRIBUTE_DETAIL,
            SysLoginLog.SYS_LOGIN_LOG,
            SysOperatingRecord.SYS_OPERATING_RECORD,
            SysPermission.SYS_PERMISSION,
            SysRole.SYS_ROLE,
            SysRolePermission.SYS_ROLE_PERMISSION,
            SysUser.SYS_USER,
            SysUserRole.SYS_USER_ROLE);
    }
}
