/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.records;


import com.wl.myshrio.generator.jooq.tables.SysAttributeDetail;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAttributeDetailRecord extends UpdatableRecordImpl<SysAttributeDetailRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -1996230396;

    /**
     * Setter for <code>shrio.sys_attribute_detail.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>shrio.sys_attribute_detail.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>shrio.sys_attribute_detail.attrId</code>. 属性id
     */
    public void setAttrid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>shrio.sys_attribute_detail.attrId</code>. 属性id
     */
    public String getAttrid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>shrio.sys_attribute_detail.name</code>. 属性明细id
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>shrio.sys_attribute_detail.name</code>. 属性明细id
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.ATTRID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysAttributeDetail.SYS_ATTRIBUTE_DETAIL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAttrid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAttrid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAttributeDetailRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAttributeDetailRecord value2(String value) {
        setAttrid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAttributeDetailRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAttributeDetailRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysAttributeDetailRecord
     */
    public SysAttributeDetailRecord() {
        super(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL);
    }

    /**
     * Create a detached, initialised SysAttributeDetailRecord
     */
    public SysAttributeDetailRecord(String id, String attrid, String name) {
        super(SysAttributeDetail.SYS_ATTRIBUTE_DETAIL);

        set(0, id);
        set(1, attrid);
        set(2, name);
    }
}
