/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.records;


import com.wl.myshrio.generator.jooq.tables.SysLoginLog;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLoginLogRecord extends UpdatableRecordImpl<SysLoginLogRecord> implements Record5<String, String, LocalDateTime, String, Integer> {

    private static final long serialVersionUID = -338864629;

    /**
     * Setter for <code>shrio.sys_login_log.id</code>. id
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>shrio.sys_login_log.id</code>. id
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>shrio.sys_login_log.uid</code>. 用户id
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>shrio.sys_login_log.uid</code>. 用户id
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>shrio.sys_login_log.loginTime</code>. 登录时间
     */
    public void setLogintime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>shrio.sys_login_log.loginTime</code>. 登录时间
     */
    public LocalDateTime getLogintime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>shrio.sys_login_log.loginIP</code>. 登录ip
     */
    public void setLoginip(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>shrio.sys_login_log.loginIP</code>. 登录ip
     */
    public String getLoginip() {
        return (String) get(3);
    }

    /**
     * Setter for <code>shrio.sys_login_log.loginTotal</code>. 登录总次数
     */
    public void setLogintotal(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>shrio.sys_login_log.loginTotal</code>. 登录总次数
     */
    public Integer getLogintotal() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, LocalDateTime, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, LocalDateTime, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysLoginLog.SYS_LOGIN_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysLoginLog.SYS_LOGIN_LOG.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return SysLoginLog.SYS_LOGIN_LOG.LOGINTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysLoginLog.SYS_LOGIN_LOG.LOGINIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return SysLoginLog.SYS_LOGIN_LOG.LOGINTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component3() {
        return getLogintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLoginip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getLogintotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getLogintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLoginip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLogintotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value2(String value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value3(LocalDateTime value) {
        setLogintime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value4(String value) {
        setLoginip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value5(Integer value) {
        setLogintotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord values(String value1, String value2, LocalDateTime value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysLoginLogRecord
     */
    public SysLoginLogRecord() {
        super(SysLoginLog.SYS_LOGIN_LOG);
    }

    /**
     * Create a detached, initialised SysLoginLogRecord
     */
    public SysLoginLogRecord(String id, String uid, LocalDateTime logintime, String loginip, Integer logintotal) {
        super(SysLoginLog.SYS_LOGIN_LOG);

        set(0, id);
        set(1, uid);
        set(2, logintime);
        set(3, loginip);
        set(4, logintotal);
    }
}
