/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.records;


import com.wl.myshrio.generator.jooq.tables.SysPermission;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionRecord extends UpdatableRecordImpl<SysPermissionRecord> implements Record12<String, String, String, String, String, Integer, String, LocalDateTime, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 123811845;

    /**
     * Setter for <code>shrio.sys_permission.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>shrio.sys_permission.name</code>. url描述
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.name</code>. url描述
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>shrio.sys_permission.url</code>. url地址
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.url</code>. url地址
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>shrio.sys_permission.requestType</code>. 请求方式
     */
    public void setRequesttype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.requestType</code>. 请求方式
     */
    public String getRequesttype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>shrio.sys_permission.fatherId</code>. 上级菜单id
     */
    public void setFatherid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.fatherId</code>. 上级菜单id
     */
    public String getFatherid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>shrio.sys_permission.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>shrio.sys_permission.type</code>. 类型：页面、按钮
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.type</code>. 类型：页面、按钮
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>shrio.sys_permission.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>shrio.sys_permission.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>shrio.sys_permission.creater</code>. 创建人
     */
    public void setCreater(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.creater</code>. 创建人
     */
    public String getCreater() {
        return (String) get(9);
    }

    /**
     * Setter for <code>shrio.sys_permission.updater</code>. 修改人
     */
    public void setUpdater(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.updater</code>. 修改人
     */
    public String getUpdater() {
        return (String) get(10);
    }

    /**
     * Setter for <code>shrio.sys_permission.iconCls</code>.
     */
    public void setIconcls(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>shrio.sys_permission.iconCls</code>.
     */
    public String getIconcls() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, Integer, String, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, Integer, String, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysPermission.SYS_PERMISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysPermission.SYS_PERMISSION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysPermission.SYS_PERMISSION.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysPermission.SYS_PERMISSION.REQUESTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysPermission.SYS_PERMISSION.FATHERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SysPermission.SYS_PERMISSION.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysPermission.SYS_PERMISSION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return SysPermission.SYS_PERMISSION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return SysPermission.SYS_PERMISSION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysPermission.SYS_PERMISSION.CREATER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysPermission.SYS_PERMISSION.UPDATER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SysPermission.SYS_PERMISSION.ICONCLS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRequesttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFatherid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCreater();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getUpdater();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getIconcls();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRequesttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFatherid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreater();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUpdater();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getIconcls();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value3(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value4(String value) {
        setRequesttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value5(String value) {
        setFatherid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value6(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value7(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value8(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value9(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value10(String value) {
        setCreater(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value11(String value) {
        setUpdater(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord value12(String value) {
        setIconcls(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, String value7, LocalDateTime value8, LocalDateTime value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysPermissionRecord
     */
    public SysPermissionRecord() {
        super(SysPermission.SYS_PERMISSION);
    }

    /**
     * Create a detached, initialised SysPermissionRecord
     */
    public SysPermissionRecord(String id, String name, String url, String requesttype, String fatherid, Integer sort, String type, LocalDateTime createTime, LocalDateTime updateTime, String creater, String updater, String iconcls) {
        super(SysPermission.SYS_PERMISSION);

        set(0, id);
        set(1, name);
        set(2, url);
        set(3, requesttype);
        set(4, fatherid);
        set(5, sort);
        set(6, type);
        set(7, createTime);
        set(8, updateTime);
        set(9, creater);
        set(10, updater);
        set(11, iconcls);
    }
}
