/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAttributeDetail implements Serializable {

    private static final long serialVersionUID = 958805353;

    private String id;
    private String attrid;
    private String name;

    public SysAttributeDetail() {}

    public SysAttributeDetail(SysAttributeDetail value) {
        this.id = value.id;
        this.attrid = value.attrid;
        this.name = value.name;
    }

    public SysAttributeDetail(
        String id,
        String attrid,
        String name
    ) {
        this.id = id;
        this.attrid = attrid;
        this.name = name;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAttrid() {
        return this.attrid;
    }

    public void setAttrid(String attrid) {
        this.attrid = attrid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysAttributeDetail (");

        sb.append(id);
        sb.append(", ").append(attrid);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
