/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOperatingRecord implements Serializable {

    private static final long serialVersionUID = 2115754280;

    private String        id;
    private String        requesturl;
    private String        remoteaddr;
    private String        params;
    private String        method;
    private LocalDateTime createTime;
    private String        uid;
    private String        flag;

    public SysOperatingRecord() {}

    public SysOperatingRecord(SysOperatingRecord value) {
        this.id = value.id;
        this.requesturl = value.requesturl;
        this.remoteaddr = value.remoteaddr;
        this.params = value.params;
        this.method = value.method;
        this.createTime = value.createTime;
        this.uid = value.uid;
        this.flag = value.flag;
    }

    public SysOperatingRecord(
        String        id,
        String        requesturl,
        String        remoteaddr,
        String        params,
        String        method,
        LocalDateTime createTime,
        String        uid,
        String        flag
    ) {
        this.id = id;
        this.requesturl = requesturl;
        this.remoteaddr = remoteaddr;
        this.params = params;
        this.method = method;
        this.createTime = createTime;
        this.uid = uid;
        this.flag = flag;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRequesturl() {
        return this.requesturl;
    }

    public void setRequesturl(String requesturl) {
        this.requesturl = requesturl;
    }

    public String getRemoteaddr() {
        return this.remoteaddr;
    }

    public void setRemoteaddr(String remoteaddr) {
        this.remoteaddr = remoteaddr;
    }

    public String getParams() {
        return this.params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysOperatingRecord (");

        sb.append(id);
        sb.append(", ").append(requesturl);
        sb.append(", ").append(remoteaddr);
        sb.append(", ").append(params);
        sb.append(", ").append(method);
        sb.append(", ").append(createTime);
        sb.append(", ").append(uid);
        sb.append(", ").append(flag);

        sb.append(")");
        return sb.toString();
    }
}
