/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermission implements Serializable {

    private static final long serialVersionUID = 1574840966;

    private String        id;
    private String        name;
    private String        url;
    private String        requesttype;
    private String        fatherid;
    private Integer       sort;
    private String        type;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private String        creater;
    private String        updater;
    private String        iconcls;

    public SysPermission() {}

    public SysPermission(SysPermission value) {
        this.id = value.id;
        this.name = value.name;
        this.url = value.url;
        this.requesttype = value.requesttype;
        this.fatherid = value.fatherid;
        this.sort = value.sort;
        this.type = value.type;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.creater = value.creater;
        this.updater = value.updater;
        this.iconcls = value.iconcls;
    }

    public SysPermission(
        String        id,
        String        name,
        String        url,
        String        requesttype,
        String        fatherid,
        Integer       sort,
        String        type,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        String        creater,
        String        updater,
        String        iconcls
    ) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.requesttype = requesttype;
        this.fatherid = fatherid;
        this.sort = sort;
        this.type = type;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.creater = creater;
        this.updater = updater;
        this.iconcls = iconcls;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getRequesttype() {
        return this.requesttype;
    }

    public void setRequesttype(String requesttype) {
        this.requesttype = requesttype;
    }

    public String getFatherid() {
        return this.fatherid;
    }

    public void setFatherid(String fatherid) {
        this.fatherid = fatherid;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public String getCreater() {
        return this.creater;
    }

    public void setCreater(String creater) {
        this.creater = creater;
    }

    public String getUpdater() {
        return this.updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }

    public String getIconcls() {
        return this.iconcls;
    }

    public void setIconcls(String iconcls) {
        this.iconcls = iconcls;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysPermission (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(requesttype);
        sb.append(", ").append(fatherid);
        sb.append(", ").append(sort);
        sb.append(", ").append(type);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(creater);
        sb.append(", ").append(updater);
        sb.append(", ").append(iconcls);

        sb.append(")");
        return sb.toString();
    }
}
