/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRole implements Serializable {

    private static final long serialVersionUID = -362473501;

    private String  id;
    private String  name;
    private String  description;
    private Integer type;

    public SysRole() {}

    public SysRole(SysRole value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.type = value.type;
    }

    public SysRole(
        String  id,
        String  name,
        String  description,
        Integer type
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.type = type;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRole (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
