/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables;


import com.wl.myshrio.generator.jooq.Indexes;
import com.wl.myshrio.generator.jooq.Keys;
import com.wl.myshrio.generator.jooq.Shrio;
import com.wl.myshrio.generator.jooq.tables.records.SysAttributeDetailRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAttributeDetail extends TableImpl<SysAttributeDetailRecord> {

    private static final long serialVersionUID = 236451858;

    /**
     * The reference instance of <code>shrio.sys_attribute_detail</code>
     */
    public static final SysAttributeDetail SYS_ATTRIBUTE_DETAIL = new SysAttributeDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysAttributeDetailRecord> getRecordType() {
        return SysAttributeDetailRecord.class;
    }

    /**
     * The column <code>shrio.sys_attribute_detail.id</code>.
     */
    public final TableField<SysAttributeDetailRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>shrio.sys_attribute_detail.attrId</code>. 属性id
     */
    public final TableField<SysAttributeDetailRecord, String> ATTRID = createField("attrId", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "属性id");

    /**
     * The column <code>shrio.sys_attribute_detail.name</code>. 属性明细id
     */
    public final TableField<SysAttributeDetailRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "属性明细id");

    /**
     * Create a <code>shrio.sys_attribute_detail</code> table reference
     */
    public SysAttributeDetail() {
        this(DSL.name("sys_attribute_detail"), null);
    }

    /**
     * Create an aliased <code>shrio.sys_attribute_detail</code> table reference
     */
    public SysAttributeDetail(String alias) {
        this(DSL.name(alias), SYS_ATTRIBUTE_DETAIL);
    }

    /**
     * Create an aliased <code>shrio.sys_attribute_detail</code> table reference
     */
    public SysAttributeDetail(Name alias) {
        this(alias, SYS_ATTRIBUTE_DETAIL);
    }

    private SysAttributeDetail(Name alias, Table<SysAttributeDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysAttributeDetail(Name alias, Table<SysAttributeDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Shrio.SHRIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_ATTRIBUTE_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysAttributeDetailRecord> getPrimaryKey() {
        return Keys.KEY_SYS_ATTRIBUTE_DETAIL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysAttributeDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<SysAttributeDetailRecord>>asList(Keys.KEY_SYS_ATTRIBUTE_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAttributeDetail as(String alias) {
        return new SysAttributeDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAttributeDetail as(Name alias) {
        return new SysAttributeDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysAttributeDetail rename(String name) {
        return new SysAttributeDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysAttributeDetail rename(Name name) {
        return new SysAttributeDetail(name, null);
    }
}
