/*
 * This file is generated by jOOQ.
*/
package com.wl.myshrio.generator.jooq.tables;


import com.wl.myshrio.generator.jooq.Indexes;
import com.wl.myshrio.generator.jooq.Keys;
import com.wl.myshrio.generator.jooq.Shrio;
import com.wl.myshrio.generator.jooq.tables.records.SysLoginLogRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLoginLog extends TableImpl<SysLoginLogRecord> {

    private static final long serialVersionUID = 503532760;

    /**
     * The reference instance of <code>shrio.sys_login_log</code>
     */
    public static final SysLoginLog SYS_LOGIN_LOG = new SysLoginLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysLoginLogRecord> getRecordType() {
        return SysLoginLogRecord.class;
    }

    /**
     * The column <code>shrio.sys_login_log.id</code>. id
     */
    public final TableField<SysLoginLogRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "id");

    /**
     * The column <code>shrio.sys_login_log.uid</code>. 用户id
     */
    public final TableField<SysLoginLogRecord, String> UID = createField("uid", org.jooq.impl.SQLDataType.VARCHAR(32), this, "用户id");

    /**
     * The column <code>shrio.sys_login_log.loginTime</code>. 登录时间
     */
    public final TableField<SysLoginLogRecord, LocalDateTime> LOGINTIME = createField("loginTime", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "登录时间");

    /**
     * The column <code>shrio.sys_login_log.loginIP</code>. 登录ip
     */
    public final TableField<SysLoginLogRecord, String> LOGINIP = createField("loginIP", org.jooq.impl.SQLDataType.VARCHAR(255), this, "登录ip");

    /**
     * The column <code>shrio.sys_login_log.loginTotal</code>. 登录总次数
     */
    public final TableField<SysLoginLogRecord, Integer> LOGINTOTAL = createField("loginTotal", org.jooq.impl.SQLDataType.INTEGER, this, "登录总次数");

    /**
     * Create a <code>shrio.sys_login_log</code> table reference
     */
    public SysLoginLog() {
        this(DSL.name("sys_login_log"), null);
    }

    /**
     * Create an aliased <code>shrio.sys_login_log</code> table reference
     */
    public SysLoginLog(String alias) {
        this(DSL.name(alias), SYS_LOGIN_LOG);
    }

    /**
     * Create an aliased <code>shrio.sys_login_log</code> table reference
     */
    public SysLoginLog(Name alias) {
        this(alias, SYS_LOGIN_LOG);
    }

    private SysLoginLog(Name alias, Table<SysLoginLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysLoginLog(Name alias, Table<SysLoginLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Shrio.SHRIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_LOGIN_LOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysLoginLogRecord> getPrimaryKey() {
        return Keys.KEY_SYS_LOGIN_LOG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysLoginLogRecord>> getKeys() {
        return Arrays.<UniqueKey<SysLoginLogRecord>>asList(Keys.KEY_SYS_LOGIN_LOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLog as(String alias) {
        return new SysLoginLog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLog as(Name alias) {
        return new SysLoginLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysLoginLog rename(String name) {
        return new SysLoginLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysLoginLog rename(Name name) {
        return new SysLoginLog(name, null);
    }
}
